### ISSUE TITLE
Beaucoup de "Unhandled exception, please reload"

### ISSUE THREAD

**Issue by Biloog29** [meziantou/meziantou.moneiz#27]
Quasiment à chaque fois que je clique sur "generate" dans "Analytics" j'ai cette erreur.

blazor.webassembly.js:1 GitHub dabatabase sha 'e0a6ac7f87b63a4d5a3be87d8bd6bf0f3d01a2d8' is equals to the current db sha 'e0a6ac7f87b63a4d5a3be87d8bd6bf0f3d01a2d8' => Do not import
blazor.webassembly.js:1 crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: Arg_IndexOutOfRangeException
System.IndexOutOfRangeException: Arg_IndexOutOfRangeException
   at Meziantou.Moneiz.Pages.Analytics.BalanceHistoryChart.OnParametersSet()
   at Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync()
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task , ComponentState )
(anonymous) @ blazor.webassembly.js:1
service-worker.js:47 Serving from cache: https://moneiz2.meziantou.net/_content/MudBlazor/MudBlazor.min.css
service-worker.js:47 Serving from cache: https://moneiz2.meziantou.net/lib/fa/css/all.css
service-worker.js:47 Serving from cache: https://moneiz2.meziantou.net/css/site.min.css
service-worker.js:47 Serving from cache: https://moneiz2.meziantou.net/Meziantou.Moneiz.styles.css
service-worker.js:47 Serving from cache: https://moneiz2.meziantou.net/manifest.json

![image](https://user-images.githubusercontent.com/67393998/157139910-1c39e365-a505-4bc0-a3c0-0a09288bc2a0.png)

**Comment by Biloog29** [comment]
blazor.webassembly.js:1 crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: Arg_IndexOutOfRangeException
System.IndexOutOfRangeException: Arg_IndexOutOfRangeException
   at Meziantou.Moneiz.Pages.Analytics.BalanceHistoryChart.OnParametersSet()
   at Microsoft.AspNetCore.Components.Rendering.ComponentState.SupplyCombinedParameters(ParameterView )

**Comment by meziantou** [comment]
Fixed by 935de98d0b3244c88cc2b7abeed2fc17695f9451
