### ISSUE TITLE
Recherche de montants

### ISSUE THREAD

**Issue by Biloog29** [meziantou/meziantou.moneiz#30]
Cce serait possible de chercher les opérations d'un certain montant ? Genre est-ce que j'ai payé 55,00€ plusieurs fois ?

**Comment by meziantou** [comment]
Oui c'est possible. Il faut mettre la valeur exacte, comme écrit dans la colonne `Amount`:
- ❌ 12
- ❌ 12.3
- ❌ 12,34
- ✔️ 12.34

Closed by d2f8a138db03f843b5fef20dfe09d75e9c7c2182, deployment in progress https://github.com/meziantou/meziantou.moneiz/actions/runs/2377933821
