### ISSUE TITLE
Analytics - Ajouter le solde minimum atteint sur la période sélectionnée

### ISSUE THREAD

**Issue by Biloog29** [meziantou/meziantou.moneiz#31]
Analytics - Ajouter le solde minimum atteint sur la période sélectionnée dans le tableau sous la big table

![image](https://user-images.githubusercontent.com/67393998/176546511-05d133d3-9b38-445e-a37c-4e8a2a29ea9d.png)

**Comment by meziantou** [comment]
J'ai ajouté les colonnes min et max.

Fixed by https://github.com/meziantou/meziantou.moneiz/commit/af7e66825221fe203cb4f594a6031a0395c65af7
